### ISSUE TITLE
Wrong status

### ISSUE THREAD

**Issue by thefirstmine** [DeathHound6/hound-commando#5]
**Describe the bug**
The Status isn't even right with the discriminator

**Expected behavior**
The Status should be with the discriminator

**Screenshots**
![Screenshot_20190924-070233_Discord](https://user-images.githubusercontent.com/53891525/65469318-a0c2e300-de99-11e9-842e-9388f970297d.jpg)

**Comment by DeathHound6** [comment]
Thanks for letting me know of this. It has now been fixed
